#!/usr/bin/env node
const { resolve } = require('path')
const { fork } = require('child_process')

const server = fork('./server', [ '5678' ],
  { cwd: resolve(__dirname, 'server')
  , stdio: 'inherit' })

server.once('message', port => {
  const options = { method: 'POST', hostname: 'localhost', port }
  const command = `cd ${resolve(__dirname, 'client')} && npm start`
  const request = require('http').request(options)
  request.write(command)
  request.end()
  process.stdin.resume() })
